[package]
name = "sev"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]

[features]
default = ["fwapi", "bin"]
fwapi = ["errno"]
bin = ["clap", "reqwest", "tiny_http"]

[dependencies]
endicon = "2.0.0"
codicon = "2.1.0"
openssl = "0.10.19"

tiny_http = { version = "0.6.2", optional = true }
reqwest = { version = "0.9.11", optional = true }
errno = { version = "0.2.4", optional = true }
clap = { version = "2.32.0", optional = true }

[[bin]]
name = "sev"
path = "src/sev.rs"
required-features = ["fwapi", "bin"]
