[package]
name = "sev"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]

[features]
default = ["fwapi"]
fwapi = ["errno"]

[dependencies]
endicon = "2.0.0"
codicon = "2.1.0"
openssl = "0.10.19"

errno = { version = "0.2.4", optional = true }
