on: [push, pull_request]
name: test
jobs:
  sw-openssl:
    name: sw openssl ${{ matrix.toolchain }} ${{ matrix.profile.name }} ${{ matrix.features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test ${{ matrix.profile.flag }} --features=${{ matrix.features }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.70.0
          - stable
        profile:
          - name: debug
          - name: release
            flag: --release
        features:
          - openssl

  sw-crypto_nossl:
    name: sw crypto_nossl ${{ matrix.toolchain }} ${{ matrix.profile.name }} ${{ matrix.features }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test ${{ matrix.profile.flag }} --features=${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.70.0
          - stable
        profile:
          - name: debug
          - name: release
            flag: --release
        features:
          - crypto_nossl
